more: 更多
random: 随便逛逛
upload: 发布时间：
loading: 加载中...
day: " 天"

# Language: 简体中文
theme:
  dark: 已切换至深色模式
  light: 已切换至浅色模式

copy:
  success: 复制成功
  error: 复制失败

time:
  day: "天前"
  hour: "小时前"
  just: "刚刚"
  min: "分钟前"
  month: "个月前"

page:
  tag: 标签
  category: 分类
  tags: 全部标签
  categories: 全部分类
  archives: 文章
  404: 页面没有找到

nav:
  site_name_title: 返回博客主页
  backtop: 返回顶部
  console: 概览

home:
  home: 推荐
  sticky: 置顶
  new: 最新
  read: 未读
  recommend: 荐
  recommendmore: 更多推荐
  archives: 全部文章

post:
  reprint: 转载或翻译
  original: 原创
  type: 该文章为${type}文章，注意版权协议
  posted: 发布于
  updated: 最后更新于
  wordcount: 文章字数
  loc: 创作于
  min: 分钟
  copyright:
    reprint: 本文是转载或翻译文章，版权归原作者所有。转载本文请联系原作者。
    original: 本文是原创文章，采用
    original_end: 协议，完整转载请注明来自
  nav:
    next: 下一篇
    prev: 上一篇


head:
  noscript: 开启JavaScript才能访问本站哦~

aside:
  postcount: "文章总数 :"
  runtime: "建站天数 :"
  updatetime: "最后更新 :"
  wordcount: "全站字数 :"
  toc: 文章目录
  tagmore: 查看全部
  avatar: 头像
  hello: 好久不见，
  back: 欢迎再次回来，

  newpost: 最近发布
  card:
    posts: "累计文章数:"
    tags: "标签总数:"
    categories: "分类总数:"

console:
  tag_tip: 标签
  tag_title: 寻找感兴趣的领域
  switch_darkmode: 昼夜切换
  switch_hideAside: 边栏显示控制
  archive_unit: 篇
  archive_all: 全部文章

sidebar:
  function: 功能
  darkmode: 显示模式
  siteinfo: 网站信息

footer:
  description: 来自${title}的文章
  learnmore: 了解更多
  randomlink: 友链
  theme: 主题

404:
  button: 返回首页

pagination:
  prev: 上一页
  next: 下一页
  to: 跳转到指定页面

about:
  other:
    oneself:
      map_title: 我现在住在
      info_title1: 生于
      info_title2: 现在职业

logs:
  tip0: "- 已展开所有短文 -"
  tip1: "- 只展示最近 #{count} 条短文 -"
  link: "链接"
